version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 2
    reviewers:
      - ccamel
    assignees:
      - ccamel
    commit-message:
      prefix: ":arrow_up:"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    reviewers:
      - ccamel
    assignees:
      - ccamel
    commit-message:
      prefix: ":arrow_up:"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 2
    reviewers:
      - ccamel
    assignees:
      - ccamel
    commit-message:
      prefix: ":arrow_up:"
