run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - forbidigo
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - lll
    - makezero
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - stylecheck
    - tparallel
    - unconvert
    - unparam
    - usetesting
    - whitespace

linters-settings:
  gci:
    sections:
      - standard
      - default
      - blank
      - dot
      - prefix(github.com/ccamel/playground-protoactor.go)
    custom-order: true
  cyclop:
    max-complexity: 20
    skip-tests: true
  funlen:
    statements: 60
    lines: 70
  godot:
    scope: declarations
  lll:
    line-length: 140

issues:
  uniq-by-line: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - source: "^//\\s*go:generate\\s"
      linters:
        - lll
    - source: "(noinspection|TODO)"
      linters:
        - godot
    - source: "//noinspection"
      linters:
        - gocritic
    - path: "_test\\.go"
      linters:
        - bodyclose
        - dupl
        - funlen
        - goconst
        - noctx
        - unused
        - wrapcheck
    - path: "_test\\.go"
      linters:
        - gosec
      text: "G115"
    - path: "_test\\.go"
      linters:
        - revive
      text: "dot-imports:"
