// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: actor/system/log/v1/log_commands.proto

package logv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_system_log_v1_log_commands_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_actor_system_log_v1_log_commands_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_actor_system_log_v1_log_commands_proto_rawDescGZIP(), []int{0}
}

func (x *LogMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_actor_system_log_v1_log_commands_proto protoreflect.FileDescriptor

var file_actor_system_log_v1_log_commands_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x6c,
	0x6f, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x22, 0x26, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42,
	0xc7, 0x01, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x6c,
	0x6f, 0x67, 0x2e, 0x76, 0x31, 0x42, 0x10, 0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4a, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x63, 0x61, 0x6d, 0x65, 0x6c, 0x2f, 0x70, 0x6c, 0x61,
	0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x6c, 0x6f, 0x67, 0x2f, 0x76, 0x31, 0x3b,
	0x6c, 0x6f, 0x67, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x53, 0x4c, 0x58, 0xaa, 0x02, 0x0d, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x2e, 0x4c, 0x6f, 0x67, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0d, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x5c, 0x4c, 0x6f, 0x67, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x19, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x5c, 0x4c, 0x6f, 0x67, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0f, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x3a, 0x3a, 0x4c, 0x6f, 0x67, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_actor_system_log_v1_log_commands_proto_rawDescOnce sync.Once
	file_actor_system_log_v1_log_commands_proto_rawDescData = file_actor_system_log_v1_log_commands_proto_rawDesc
)

func file_actor_system_log_v1_log_commands_proto_rawDescGZIP() []byte {
	file_actor_system_log_v1_log_commands_proto_rawDescOnce.Do(func() {
		file_actor_system_log_v1_log_commands_proto_rawDescData = protoimpl.X.CompressGZIP(file_actor_system_log_v1_log_commands_proto_rawDescData)
	})
	return file_actor_system_log_v1_log_commands_proto_rawDescData
}

var file_actor_system_log_v1_log_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_actor_system_log_v1_log_commands_proto_goTypes = []interface{}{
	(*LogMessage)(nil), // 0: system.log.v1.LogMessage
}
var file_actor_system_log_v1_log_commands_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_actor_system_log_v1_log_commands_proto_init() }
func file_actor_system_log_v1_log_commands_proto_init() {
	if File_actor_system_log_v1_log_commands_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_actor_system_log_v1_log_commands_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_actor_system_log_v1_log_commands_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_actor_system_log_v1_log_commands_proto_goTypes,
		DependencyIndexes: file_actor_system_log_v1_log_commands_proto_depIdxs,
		MessageInfos:      file_actor_system_log_v1_log_commands_proto_msgTypes,
	}.Build()
	File_actor_system_log_v1_log_commands_proto = out.File
	file_actor_system_log_v1_log_commands_proto_rawDesc = nil
	file_actor_system_log_v1_log_commands_proto_goTypes = nil
	file_actor_system_log_v1_log_commands_proto_depIdxs = nil
}
