name: Lint / Proto

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-proto:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Find changed proto files
        id: changed-proto-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: |
            internal/**/*.proto

      - name: Lint proto files
        if: steps.changed-proto-files.outputs.any_changed == 'true'
        run: |
          make lint-proto
