name: Lint / Markdown

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-markdown:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Lint regular markdown files
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: "**/*.md"
